// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kVinsom/Bank-backend/internal/mocks/exchange_rate (interfaces: RankingRepositoryClient)

// Package exchange_rate is a generated GoMock package.
package exchange_rate

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	exchange_ranking "github.com/kVinsom/Bank-proto/exchange_rate"
	grpc "google.golang.org/grpc"
)

// MockRankingRepositoryClient is a mock of RankingRepositoryClient interface.
type MockRankingRepositoryClient struct {
	ctrl     *gomock.Controller
	recorder *MockRankingRepositoryClientMockRecorder
}

// MockRankingRepositoryClientMockRecorder is the mock recorder for MockRankingRepositoryClient.
type MockRankingRepositoryClientMockRecorder struct {
	mock *MockRankingRepositoryClient
}

// NewMockRankingRepositoryClient creates a new mock instance.
func NewMockRankingRepositoryClient(ctrl *gomock.Controller) *MockRankingRepositoryClient {
	mock := &MockRankingRepositoryClient{ctrl: ctrl}
	mock.recorder = &MockRankingRepositoryClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRankingRepositoryClient) EXPECT() *MockRankingRepositoryClientMockRecorder {
	return m.recorder
}

// GetAllRanking mocks base method.
func (m *MockRankingRepositoryClient) GetAllRanking(arg0 context.Context, arg1 *exchange_ranking.GetAllRankingRequest, arg2 ...grpc.CallOption) (*exchange_ranking.RankingList, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAllRanking", varargs...)
	ret0, _ := ret[0].(*exchange_ranking.RankingList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllRanking indicates an expected call of GetAllRanking.
func (mr *MockRankingRepositoryClientMockRecorder) GetAllRanking(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllRanking", reflect.TypeOf((*MockRankingRepositoryClient)(nil).GetAllRanking), varargs...)
}

// GetRelativeRanking mocks base method.
func (m *MockRankingRepositoryClient) GetRelativeRanking(arg0 context.Context, arg1 *exchange_ranking.GetRelativeRankingRequest, arg2 ...grpc.CallOption) (*exchange_ranking.Ranking, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetRelativeRanking", varargs...)
	ret0, _ := ret[0].(*exchange_ranking.Ranking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRelativeRanking indicates an expected call of GetRelativeRanking.
func (mr *MockRankingRepositoryClientMockRecorder) GetRelativeRanking(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelativeRanking", reflect.TypeOf((*MockRankingRepositoryClient)(nil).GetRelativeRanking), varargs...)
}
