// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kVinsom/Bank-backend/internal/mocks/repositories (interfaces: AccountRepositoryClient)

// Package repositories is a generated GoMock package.
package repositories

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	account "github.com/kVinsom/Bank-proto/repository/account"
	common "github.com/kVinsom/Bank-proto/repository/common"
	grpc "google.golang.org/grpc"
)

// MockAccountRepositoryClient is a mock of AccountRepositoryClient interface.
type MockAccountRepositoryClient struct {
	ctrl     *gomock.Controller
	recorder *MockAccountRepositoryClientMockRecorder
}

// MockAccountRepositoryClientMockRecorder is the mock recorder for MockAccountRepositoryClient.
type MockAccountRepositoryClientMockRecorder struct {
	mock *MockAccountRepositoryClient
}

// NewMockAccountRepositoryClient creates a new mock instance.
func NewMockAccountRepositoryClient(ctrl *gomock.Controller) *MockAccountRepositoryClient {
	mock := &MockAccountRepositoryClient{ctrl: ctrl}
	mock.recorder = &MockAccountRepositoryClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountRepositoryClient) EXPECT() *MockAccountRepositoryClientMockRecorder {
	return m.recorder
}

// Blocking mocks base method.
func (m *MockAccountRepositoryClient) Blocking(arg0 context.Context, arg1 *common.IdRequest, arg2 ...grpc.CallOption) (*account.Account, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Blocking", varargs...)
	ret0, _ := ret[0].(*account.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Blocking indicates an expected call of Blocking.
func (mr *MockAccountRepositoryClientMockRecorder) Blocking(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Blocking", reflect.TypeOf((*MockAccountRepositoryClient)(nil).Blocking), varargs...)
}

// Close mocks base method.
func (m *MockAccountRepositoryClient) Close(arg0 context.Context, arg1 *common.IdRequest, arg2 ...grpc.CallOption) (*account.Account, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Close", varargs...)
	ret0, _ := ret[0].(*account.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Close indicates an expected call of Close.
func (mr *MockAccountRepositoryClientMockRecorder) Close(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockAccountRepositoryClient)(nil).Close), varargs...)
}

// Create mocks base method.
func (m *MockAccountRepositoryClient) Create(arg0 context.Context, arg1 *account.Account, arg2 ...grpc.CallOption) (*account.Account, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*account.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAccountRepositoryClientMockRecorder) Create(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAccountRepositoryClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockAccountRepositoryClient) Delete(arg0 context.Context, arg1 *common.IdRequest, arg2 ...grpc.CallOption) (*common.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*common.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockAccountRepositoryClientMockRecorder) Delete(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAccountRepositoryClient)(nil).Delete), varargs...)
}

// GetAll mocks base method.
func (m *MockAccountRepositoryClient) GetAll(arg0 context.Context, arg1 *common.Empty, arg2 ...grpc.CallOption) (*account.AccountList, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAll", varargs...)
	ret0, _ := ret[0].(*account.AccountList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockAccountRepositoryClientMockRecorder) GetAll(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockAccountRepositoryClient)(nil).GetAll), varargs...)
}

// GetById mocks base method.
func (m *MockAccountRepositoryClient) GetById(arg0 context.Context, arg1 *common.IdRequest, arg2 ...grpc.CallOption) (*account.Account, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetById", varargs...)
	ret0, _ := ret[0].(*account.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockAccountRepositoryClientMockRecorder) GetById(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockAccountRepositoryClient)(nil).GetById), varargs...)
}

// GetByUser mocks base method.
func (m *MockAccountRepositoryClient) GetByUser(arg0 context.Context, arg1 *common.UserIdRequest, arg2 ...grpc.CallOption) (*account.AccountList, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByUser", varargs...)
	ret0, _ := ret[0].(*account.AccountList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUser indicates an expected call of GetByUser.
func (mr *MockAccountRepositoryClientMockRecorder) GetByUser(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUser", reflect.TypeOf((*MockAccountRepositoryClient)(nil).GetByUser), varargs...)
}

// Update mocks base method.
func (m *MockAccountRepositoryClient) Update(arg0 context.Context, arg1 *account.UpdateAccountRequest, arg2 ...grpc.CallOption) (*account.Account, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*account.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockAccountRepositoryClientMockRecorder) Update(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAccountRepositoryClient)(nil).Update), varargs...)
}
