// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kVinsom/Bank-backend/internal/mocks/repositories (interfaces: CardRepositoryClient)

// Package repositories is a generated GoMock package.
package repositories

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	card "github.com/kVinsom/Bank-proto/repository/card"
	common "github.com/kVinsom/Bank-proto/repository/common"
	grpc "google.golang.org/grpc"
)

// MockCardRepositoryClient is a mock of CardRepositoryClient interface.
type MockCardRepositoryClient struct {
	ctrl     *gomock.Controller
	recorder *MockCardRepositoryClientMockRecorder
}

// MockCardRepositoryClientMockRecorder is the mock recorder for MockCardRepositoryClient.
type MockCardRepositoryClientMockRecorder struct {
	mock *MockCardRepositoryClient
}

// NewMockCardRepositoryClient creates a new mock instance.
func NewMockCardRepositoryClient(ctrl *gomock.Controller) *MockCardRepositoryClient {
	mock := &MockCardRepositoryClient{ctrl: ctrl}
	mock.recorder = &MockCardRepositoryClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCardRepositoryClient) EXPECT() *MockCardRepositoryClientMockRecorder {
	return m.recorder
}

// Blocking mocks base method.
func (m *MockCardRepositoryClient) Blocking(arg0 context.Context, arg1 *common.IdRequest, arg2 ...grpc.CallOption) (*card.Card, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Blocking", varargs...)
	ret0, _ := ret[0].(*card.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Blocking indicates an expected call of Blocking.
func (mr *MockCardRepositoryClientMockRecorder) Blocking(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Blocking", reflect.TypeOf((*MockCardRepositoryClient)(nil).Blocking), varargs...)
}

// Create mocks base method.
func (m *MockCardRepositoryClient) Create(arg0 context.Context, arg1 *card.Card, arg2 ...grpc.CallOption) (*card.Card, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*card.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCardRepositoryClientMockRecorder) Create(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCardRepositoryClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockCardRepositoryClient) Delete(arg0 context.Context, arg1 *common.IdRequest, arg2 ...grpc.CallOption) (*common.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*common.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockCardRepositoryClientMockRecorder) Delete(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCardRepositoryClient)(nil).Delete), varargs...)
}

// GetAll mocks base method.
func (m *MockCardRepositoryClient) GetAll(arg0 context.Context, arg1 *common.Empty, arg2 ...grpc.CallOption) (*card.CardList, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAll", varargs...)
	ret0, _ := ret[0].(*card.CardList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockCardRepositoryClientMockRecorder) GetAll(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockCardRepositoryClient)(nil).GetAll), varargs...)
}

// GetById mocks base method.
func (m *MockCardRepositoryClient) GetById(arg0 context.Context, arg1 *common.IdRequest, arg2 ...grpc.CallOption) (*card.Card, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetById", varargs...)
	ret0, _ := ret[0].(*card.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockCardRepositoryClientMockRecorder) GetById(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockCardRepositoryClient)(nil).GetById), varargs...)
}

// GetByNumber mocks base method.
func (m *MockCardRepositoryClient) GetByNumber(arg0 context.Context, arg1 *card.CardNumberRequest, arg2 ...grpc.CallOption) (*card.Card, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByNumber", varargs...)
	ret0, _ := ret[0].(*card.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByNumber indicates an expected call of GetByNumber.
func (mr *MockCardRepositoryClientMockRecorder) GetByNumber(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByNumber", reflect.TypeOf((*MockCardRepositoryClient)(nil).GetByNumber), varargs...)
}

// GetByUser mocks base method.
func (m *MockCardRepositoryClient) GetByUser(arg0 context.Context, arg1 *common.UserIdRequest, arg2 ...grpc.CallOption) (*card.CardList, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByUser", varargs...)
	ret0, _ := ret[0].(*card.CardList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUser indicates an expected call of GetByUser.
func (mr *MockCardRepositoryClientMockRecorder) GetByUser(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUser", reflect.TypeOf((*MockCardRepositoryClient)(nil).GetByUser), varargs...)
}
