// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kVinsom/Bank-backend/internal/mocks/repositories (interfaces: CreditRepositoryClient)

// Package repositories is a generated GoMock package.
package repositories

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	common "github.com/kVinsom/Bank-proto/repository/common"
	credit "github.com/kVinsom/Bank-proto/repository/credit"
	grpc "google.golang.org/grpc"
)

// MockCreditRepositoryClient is a mock of CreditRepositoryClient interface.
type MockCreditRepositoryClient struct {
	ctrl     *gomock.Controller
	recorder *MockCreditRepositoryClientMockRecorder
}

// MockCreditRepositoryClientMockRecorder is the mock recorder for MockCreditRepositoryClient.
type MockCreditRepositoryClientMockRecorder struct {
	mock *MockCreditRepositoryClient
}

// NewMockCreditRepositoryClient creates a new mock instance.
func NewMockCreditRepositoryClient(ctrl *gomock.Controller) *MockCreditRepositoryClient {
	mock := &MockCreditRepositoryClient{ctrl: ctrl}
	mock.recorder = &MockCreditRepositoryClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreditRepositoryClient) EXPECT() *MockCreditRepositoryClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCreditRepositoryClient) Create(arg0 context.Context, arg1 *credit.Credit, arg2 ...grpc.CallOption) (*credit.Credit, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*credit.Credit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCreditRepositoryClientMockRecorder) Create(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCreditRepositoryClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockCreditRepositoryClient) Delete(arg0 context.Context, arg1 *common.IdRequest, arg2 ...grpc.CallOption) (*common.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*common.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockCreditRepositoryClientMockRecorder) Delete(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCreditRepositoryClient)(nil).Delete), varargs...)
}

// GetAll mocks base method.
func (m *MockCreditRepositoryClient) GetAll(arg0 context.Context, arg1 *common.Empty, arg2 ...grpc.CallOption) (*credit.CreditList, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAll", varargs...)
	ret0, _ := ret[0].(*credit.CreditList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockCreditRepositoryClientMockRecorder) GetAll(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockCreditRepositoryClient)(nil).GetAll), varargs...)
}

// GetById mocks base method.
func (m *MockCreditRepositoryClient) GetById(arg0 context.Context, arg1 *common.IdRequest, arg2 ...grpc.CallOption) (*credit.Credit, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetById", varargs...)
	ret0, _ := ret[0].(*credit.Credit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockCreditRepositoryClientMockRecorder) GetById(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockCreditRepositoryClient)(nil).GetById), varargs...)
}

// GetByUser mocks base method.
func (m *MockCreditRepositoryClient) GetByUser(arg0 context.Context, arg1 *common.UserIdRequest, arg2 ...grpc.CallOption) (*credit.CreditList, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByUser", varargs...)
	ret0, _ := ret[0].(*credit.CreditList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUser indicates an expected call of GetByUser.
func (mr *MockCreditRepositoryClientMockRecorder) GetByUser(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUser", reflect.TypeOf((*MockCreditRepositoryClient)(nil).GetByUser), varargs...)
}

// Repay mocks base method.
func (m *MockCreditRepositoryClient) Repay(arg0 context.Context, arg1 *common.AmountRequest, arg2 ...grpc.CallOption) (*credit.Credit, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Repay", varargs...)
	ret0, _ := ret[0].(*credit.Credit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Repay indicates an expected call of Repay.
func (mr *MockCreditRepositoryClientMockRecorder) Repay(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Repay", reflect.TypeOf((*MockCreditRepositoryClient)(nil).Repay), varargs...)
}
