// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kVinsom/Bank-backend/internal/mocks/repositories (interfaces: CurrencyRepositoryClient)

// Package repositories is a generated GoMock package.
package repositories

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	common "github.com/kVinsom/Bank-proto/repository/common"
	currency "github.com/kVinsom/Bank-proto/repository/currency"
	grpc "google.golang.org/grpc"
)

// MockCurrencyRepositoryClient is a mock of CurrencyRepositoryClient interface.
type MockCurrencyRepositoryClient struct {
	ctrl     *gomock.Controller
	recorder *MockCurrencyRepositoryClientMockRecorder
}

// MockCurrencyRepositoryClientMockRecorder is the mock recorder for MockCurrencyRepositoryClient.
type MockCurrencyRepositoryClientMockRecorder struct {
	mock *MockCurrencyRepositoryClient
}

// NewMockCurrencyRepositoryClient creates a new mock instance.
func NewMockCurrencyRepositoryClient(ctrl *gomock.Controller) *MockCurrencyRepositoryClient {
	mock := &MockCurrencyRepositoryClient{ctrl: ctrl}
	mock.recorder = &MockCurrencyRepositoryClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCurrencyRepositoryClient) EXPECT() *MockCurrencyRepositoryClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCurrencyRepositoryClient) Create(arg0 context.Context, arg1 *currency.Currency, arg2 ...grpc.CallOption) (*currency.Currency, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*currency.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCurrencyRepositoryClientMockRecorder) Create(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCurrencyRepositoryClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockCurrencyRepositoryClient) Delete(arg0 context.Context, arg1 *common.IdRequest, arg2 ...grpc.CallOption) (*common.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*common.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockCurrencyRepositoryClientMockRecorder) Delete(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCurrencyRepositoryClient)(nil).Delete), varargs...)
}

// GetAll mocks base method.
func (m *MockCurrencyRepositoryClient) GetAll(arg0 context.Context, arg1 *common.Empty, arg2 ...grpc.CallOption) (*currency.CurrencyList, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAll", varargs...)
	ret0, _ := ret[0].(*currency.CurrencyList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockCurrencyRepositoryClientMockRecorder) GetAll(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockCurrencyRepositoryClient)(nil).GetAll), varargs...)
}

// GetById mocks base method.
func (m *MockCurrencyRepositoryClient) GetById(arg0 context.Context, arg1 *common.IdRequest, arg2 ...grpc.CallOption) (*currency.Currency, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetById", varargs...)
	ret0, _ := ret[0].(*currency.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockCurrencyRepositoryClientMockRecorder) GetById(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockCurrencyRepositoryClient)(nil).GetById), varargs...)
}

// GetByIso mocks base method.
func (m *MockCurrencyRepositoryClient) GetByIso(arg0 context.Context, arg1 *currency.IsoCodeRequest, arg2 ...grpc.CallOption) (*currency.Currency, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByIso", varargs...)
	ret0, _ := ret[0].(*currency.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIso indicates an expected call of GetByIso.
func (mr *MockCurrencyRepositoryClientMockRecorder) GetByIso(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIso", reflect.TypeOf((*MockCurrencyRepositoryClient)(nil).GetByIso), varargs...)
}

// GetBySymbol mocks base method.
func (m *MockCurrencyRepositoryClient) GetBySymbol(arg0 context.Context, arg1 *currency.SymbolRequest, arg2 ...grpc.CallOption) (*currency.Currency, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetBySymbol", varargs...)
	ret0, _ := ret[0].(*currency.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySymbol indicates an expected call of GetBySymbol.
func (mr *MockCurrencyRepositoryClientMockRecorder) GetBySymbol(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySymbol", reflect.TypeOf((*MockCurrencyRepositoryClient)(nil).GetBySymbol), varargs...)
}

// Update mocks base method.
func (m *MockCurrencyRepositoryClient) Update(arg0 context.Context, arg1 *currency.UpdateCurrencyRequest, arg2 ...grpc.CallOption) (*currency.Currency, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*currency.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCurrencyRepositoryClientMockRecorder) Update(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCurrencyRepositoryClient)(nil).Update), varargs...)
}
