// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kVinsom/Bank-backend/internal/mocks/repositories (interfaces: DepositRepositoryClient)

// Package repositories is a generated GoMock package.
package repositories

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	common "github.com/kVinsom/Bank-proto/repository/common"
	deposit "github.com/kVinsom/Bank-proto/repository/deposit"
	grpc "google.golang.org/grpc"
)

// MockDepositRepositoryClient is a mock of DepositRepositoryClient interface.
type MockDepositRepositoryClient struct {
	ctrl     *gomock.Controller
	recorder *MockDepositRepositoryClientMockRecorder
}

// MockDepositRepositoryClientMockRecorder is the mock recorder for MockDepositRepositoryClient.
type MockDepositRepositoryClientMockRecorder struct {
	mock *MockDepositRepositoryClient
}

// NewMockDepositRepositoryClient creates a new mock instance.
func NewMockDepositRepositoryClient(ctrl *gomock.Controller) *MockDepositRepositoryClient {
	mock := &MockDepositRepositoryClient{ctrl: ctrl}
	mock.recorder = &MockDepositRepositoryClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDepositRepositoryClient) EXPECT() *MockDepositRepositoryClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDepositRepositoryClient) Create(arg0 context.Context, arg1 *deposit.Deposit, arg2 ...grpc.CallOption) (*deposit.Deposit, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*deposit.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDepositRepositoryClientMockRecorder) Create(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDepositRepositoryClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockDepositRepositoryClient) Delete(arg0 context.Context, arg1 *common.IdRequest, arg2 ...grpc.CallOption) (*common.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*common.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockDepositRepositoryClientMockRecorder) Delete(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDepositRepositoryClient)(nil).Delete), varargs...)
}

// GetAll mocks base method.
func (m *MockDepositRepositoryClient) GetAll(arg0 context.Context, arg1 *common.Empty, arg2 ...grpc.CallOption) (*deposit.DepositList, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAll", varargs...)
	ret0, _ := ret[0].(*deposit.DepositList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockDepositRepositoryClientMockRecorder) GetAll(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockDepositRepositoryClient)(nil).GetAll), varargs...)
}

// GetById mocks base method.
func (m *MockDepositRepositoryClient) GetById(arg0 context.Context, arg1 *common.IdRequest, arg2 ...grpc.CallOption) (*deposit.Deposit, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetById", varargs...)
	ret0, _ := ret[0].(*deposit.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockDepositRepositoryClientMockRecorder) GetById(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockDepositRepositoryClient)(nil).GetById), varargs...)
}

// GetByUser mocks base method.
func (m *MockDepositRepositoryClient) GetByUser(arg0 context.Context, arg1 *common.UserIdRequest, arg2 ...grpc.CallOption) (*deposit.DepositList, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByUser", varargs...)
	ret0, _ := ret[0].(*deposit.DepositList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUser indicates an expected call of GetByUser.
func (mr *MockDepositRepositoryClientMockRecorder) GetByUser(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUser", reflect.TypeOf((*MockDepositRepositoryClient)(nil).GetByUser), varargs...)
}

// Replenish mocks base method.
func (m *MockDepositRepositoryClient) Replenish(arg0 context.Context, arg1 *common.AmountRequest, arg2 ...grpc.CallOption) (*deposit.Deposit, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Replenish", varargs...)
	ret0, _ := ret[0].(*deposit.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Replenish indicates an expected call of Replenish.
func (mr *MockDepositRepositoryClientMockRecorder) Replenish(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replenish", reflect.TypeOf((*MockDepositRepositoryClient)(nil).Replenish), varargs...)
}
