// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kVinsom/Bank-backend/internal/mocks/repositories (interfaces: UserRepositoryClient)

// Package repositories is a generated GoMock package.
package repositories

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	common "github.com/kVinsom/Bank-proto/repository/common"
	user "github.com/kVinsom/Bank-proto/repository/user"
	grpc "google.golang.org/grpc"
)

// MockUserRepositoryClient is a mock of UserRepositoryClient interface.
type MockUserRepositoryClient struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryClientMockRecorder
}

// MockUserRepositoryClientMockRecorder is the mock recorder for MockUserRepositoryClient.
type MockUserRepositoryClientMockRecorder struct {
	mock *MockUserRepositoryClient
}

// NewMockUserRepositoryClient creates a new mock instance.
func NewMockUserRepositoryClient(ctrl *gomock.Controller) *MockUserRepositoryClient {
	mock := &MockUserRepositoryClient{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepositoryClient) EXPECT() *MockUserRepositoryClientMockRecorder {
	return m.recorder
}

// ChangePassword mocks base method.
func (m *MockUserRepositoryClient) ChangePassword(arg0 context.Context, arg1 *user.ChangePasswordRequest, arg2 ...grpc.CallOption) (*user.User, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ChangePassword", varargs...)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockUserRepositoryClientMockRecorder) ChangePassword(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockUserRepositoryClient)(nil).ChangePassword), varargs...)
}

// Create mocks base method.
func (m *MockUserRepositoryClient) Create(arg0 context.Context, arg1 *user.User, arg2 ...grpc.CallOption) (*user.User, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryClientMockRecorder) Create(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepositoryClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockUserRepositoryClient) Delete(arg0 context.Context, arg1 *common.IdRequest, arg2 ...grpc.CallOption) (*common.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*common.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockUserRepositoryClientMockRecorder) Delete(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserRepositoryClient)(nil).Delete), varargs...)
}

// GetAll mocks base method.
func (m *MockUserRepositoryClient) GetAll(arg0 context.Context, arg1 *common.Empty, arg2 ...grpc.CallOption) (*user.UserList, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAll", varargs...)
	ret0, _ := ret[0].(*user.UserList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockUserRepositoryClientMockRecorder) GetAll(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockUserRepositoryClient)(nil).GetAll), varargs...)
}

// GetByEmail mocks base method.
func (m *MockUserRepositoryClient) GetByEmail(arg0 context.Context, arg1 *user.EmailRequest, arg2 ...grpc.CallOption) (*user.User, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByEmail", varargs...)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepositoryClientMockRecorder) GetByEmail(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepositoryClient)(nil).GetByEmail), varargs...)
}

// GetById mocks base method.
func (m *MockUserRepositoryClient) GetById(arg0 context.Context, arg1 *common.IdRequest, arg2 ...grpc.CallOption) (*user.User, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetById", varargs...)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockUserRepositoryClientMockRecorder) GetById(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockUserRepositoryClient)(nil).GetById), varargs...)
}

// GetByPhoneNumber mocks base method.
func (m *MockUserRepositoryClient) GetByPhoneNumber(arg0 context.Context, arg1 *user.PhoneNumberRequest, arg2 ...grpc.CallOption) (*user.User, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByPhoneNumber", varargs...)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPhoneNumber indicates an expected call of GetByPhoneNumber.
func (mr *MockUserRepositoryClientMockRecorder) GetByPhoneNumber(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPhoneNumber", reflect.TypeOf((*MockUserRepositoryClient)(nil).GetByPhoneNumber), varargs...)
}

// Update mocks base method.
func (m *MockUserRepositoryClient) Update(arg0 context.Context, arg1 *user.UpdateUserRequest, arg2 ...grpc.CallOption) (*user.User, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUserRepositoryClientMockRecorder) Update(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepositoryClient)(nil).Update), varargs...)
}
