// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: notification.proto

package notification

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityType int32

const (
	EntityType_ENTITY_UNSPECIFIED EntityType = 0
	EntityType_ACCOUNT            EntityType = 1
	EntityType_CARD               EntityType = 2
	EntityType_CREDIT             EntityType = 3
	EntityType_DEPOSIT            EntityType = 4
	EntityType_USER               EntityType = 5
	EntityType_CURRENCY           EntityType = 6
)

// Enum value maps for EntityType.
var (
	EntityType_name = map[int32]string{
		0: "ENTITY_UNSPECIFIED",
		1: "ACCOUNT",
		2: "CARD",
		3: "CREDIT",
		4: "DEPOSIT",
		5: "USER",
		6: "CURRENCY",
	}
	EntityType_value = map[string]int32{
		"ENTITY_UNSPECIFIED": 0,
		"ACCOUNT":            1,
		"CARD":               2,
		"CREDIT":             3,
		"DEPOSIT":            4,
		"USER":               5,
		"CURRENCY":           6,
	}
)

func (x EntityType) Enum() *EntityType {
	p := new(EntityType)
	*p = x
	return p
}

func (x EntityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityType) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_proto_enumTypes[0].Descriptor()
}

func (EntityType) Type() protoreflect.EnumType {
	return &file_notification_proto_enumTypes[0]
}

func (x EntityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityType.Descriptor instead.
func (EntityType) EnumDescriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{0}
}

type ActionType int32

const (
	ActionType_ACTION_UNSPECIFIED ActionType = 0
	ActionType_CREATE             ActionType = 1
	ActionType_DELETE             ActionType = 2
	ActionType_BLOCK              ActionType = 3
	ActionType_CLOSE              ActionType = 4
	ActionType_REPAY              ActionType = 5
	ActionType_REPLENISH          ActionType = 6
	ActionType_CHANGE_PASSWORD    ActionType = 7
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "CREATE",
		2: "DELETE",
		3: "BLOCK",
		4: "CLOSE",
		5: "REPAY",
		6: "REPLENISH",
		7: "CHANGE_PASSWORD",
	}
	ActionType_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"CREATE":             1,
		"DELETE":             2,
		"BLOCK":              3,
		"CLOSE":              4,
		"REPAY":              5,
		"REPLENISH":          6,
		"CHANGE_PASSWORD":    7,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_proto_enumTypes[1].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_notification_proto_enumTypes[1]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{1}
}

type NotificationEventRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Entity   EntityType             `protobuf:"varint,1,opt,name=entity,proto3,enum=notification.EntityType" json:"entity,omitempty"`
	Action   ActionType             `protobuf:"varint,2,opt,name=action,proto3,enum=notification.ActionType" json:"action,omitempty"`
	EntityId int64                  `protobuf:"varint,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	UserId        int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationEventRequest) Reset() {
	*x = NotificationEventRequest{}
	mi := &file_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationEventRequest) ProtoMessage() {}

func (x *NotificationEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationEventRequest.ProtoReflect.Descriptor instead.
func (*NotificationEventRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationEventRequest) GetEntity() EntityType {
	if x != nil {
		return x.Entity
	}
	return EntityType_ENTITY_UNSPECIFIED
}

func (x *NotificationEventRequest) GetAction() ActionType {
	if x != nil {
		return x.Action
	}
	return ActionType_ACTION_UNSPECIFIED
}

func (x *NotificationEventRequest) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *NotificationEventRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type NotificationEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationEventResponse) Reset() {
	*x = NotificationEventResponse{}
	mi := &file_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationEventResponse) ProtoMessage() {}

func (x *NotificationEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationEventResponse.ProtoReflect.Descriptor instead.
func (*NotificationEventResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_notification_proto protoreflect.FileDescriptor

const file_notification_proto_rawDesc = "" +
	"\n" +
	"\x12notification.proto\x12\fnotification\"\xb4\x01\n" +
	"\x18NotificationEventRequest\x120\n" +
	"\x06entity\x18\x01 \x01(\x0e2\x18.notification.EntityTypeR\x06entity\x120\n" +
	"\x06action\x18\x02 \x01(\x0e2\x18.notification.ActionTypeR\x06action\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\x03R\bentityId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\"5\n" +
	"\x19NotificationEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*l\n" +
	"\n" +
	"EntityType\x12\x16\n" +
	"\x12ENTITY_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aACCOUNT\x10\x01\x12\b\n" +
	"\x04CARD\x10\x02\x12\n" +
	"\n" +
	"\x06CREDIT\x10\x03\x12\v\n" +
	"\aDEPOSIT\x10\x04\x12\b\n" +
	"\x04USER\x10\x05\x12\f\n" +
	"\bCURRENCY\x10\x06*\x81\x01\n" +
	"\n" +
	"ActionType\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06CREATE\x10\x01\x12\n" +
	"\n" +
	"\x06DELETE\x10\x02\x12\t\n" +
	"\x05BLOCK\x10\x03\x12\t\n" +
	"\x05CLOSE\x10\x04\x12\t\n" +
	"\x05REPAY\x10\x05\x12\r\n" +
	"\tREPLENISH\x10\x06\x12\x13\n" +
	"\x0fCHANGE_PASSWORD\x10\a2s\n" +
	"\x13NotificationService\x12\\\n" +
	"\tSendEvent\x12&.notification.NotificationEventRequest\x1a'.notification.NotificationEventResponseB\x10Z\x0e./notificationb\x06proto3"

var (
	file_notification_proto_rawDescOnce sync.Once
	file_notification_proto_rawDescData []byte
)

func file_notification_proto_rawDescGZIP() []byte {
	file_notification_proto_rawDescOnce.Do(func() {
		file_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)))
	})
	return file_notification_proto_rawDescData
}

var file_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_notification_proto_goTypes = []any{
	(EntityType)(0),                   // 0: notification.EntityType
	(ActionType)(0),                   // 1: notification.ActionType
	(*NotificationEventRequest)(nil),  // 2: notification.NotificationEventRequest
	(*NotificationEventResponse)(nil), // 3: notification.NotificationEventResponse
}
var file_notification_proto_depIdxs = []int32{
	0, // 0: notification.NotificationEventRequest.entity:type_name -> notification.EntityType
	1, // 1: notification.NotificationEventRequest.action:type_name -> notification.ActionType
	2, // 2: notification.NotificationService.SendEvent:input_type -> notification.NotificationEventRequest
	3, // 3: notification.NotificationService.SendEvent:output_type -> notification.NotificationEventResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_notification_proto_init() }
func file_notification_proto_init() {
	if File_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_proto_goTypes,
		DependencyIndexes: file_notification_proto_depIdxs,
		EnumInfos:         file_notification_proto_enumTypes,
		MessageInfos:      file_notification_proto_msgTypes,
	}.Build()
	File_notification_proto = out.File
	file_notification_proto_goTypes = nil
	file_notification_proto_depIdxs = nil
}
