// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	core "github.com/kVinsom/Bank-repository-service/pkg/core"
)

// MockICardService is a mock of ICardService interface.
type MockICardService struct {
	ctrl     *gomock.Controller
	recorder *MockICardServiceMockRecorder
}

// MockICardServiceMockRecorder is the mock recorder for MockICardService.
type MockICardServiceMockRecorder struct {
	mock *MockICardService
}

// NewMockICardService creates a new mock instance.
func NewMockICardService(ctrl *gomock.Controller) *MockICardService {
	mock := &MockICardService{ctrl: ctrl}
	mock.recorder = &MockICardServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICardService) EXPECT() *MockICardServiceMockRecorder {
	return m.recorder
}

// Blocking mocks base method.
func (m *MockICardService) Blocking(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Blocking", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Blocking indicates an expected call of Blocking.
func (mr *MockICardServiceMockRecorder) Blocking(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Blocking", reflect.TypeOf((*MockICardService)(nil).Blocking), arg0, arg1)
}

// Create mocks base method.
func (m *MockICardService) Create(arg0 context.Context, arg1 *core.CardCreateInput) (*core.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*core.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockICardServiceMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockICardService)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockICardService) Delete(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockICardServiceMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockICardService)(nil).Delete), arg0, arg1)
}

// GetAll mocks base method.
func (m *MockICardService) GetAll(arg0 context.Context) ([]core.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0)
	ret0, _ := ret[0].([]core.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockICardServiceMockRecorder) GetAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockICardService)(nil).GetAll), arg0)
}

// GetById mocks base method.
func (m *MockICardService) GetById(arg0 context.Context, arg1 int64) (*core.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", arg0, arg1)
	ret0, _ := ret[0].(*core.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockICardServiceMockRecorder) GetById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockICardService)(nil).GetById), arg0, arg1)
}

// GetByNumber mocks base method.
func (m *MockICardService) GetByNumber(arg0 context.Context, arg1 string) (*core.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByNumber", arg0, arg1)
	ret0, _ := ret[0].(*core.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByNumber indicates an expected call of GetByNumber.
func (mr *MockICardServiceMockRecorder) GetByNumber(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByNumber", reflect.TypeOf((*MockICardService)(nil).GetByNumber), arg0, arg1)
}

// GetByUser mocks base method.
func (m *MockICardService) GetByUser(arg0 context.Context, arg1 int64) ([]core.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUser", arg0, arg1)
	ret0, _ := ret[0].([]core.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUser indicates an expected call of GetByUser.
func (mr *MockICardServiceMockRecorder) GetByUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUser", reflect.TypeOf((*MockICardService)(nil).GetByUser), arg0, arg1)
}
