// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	core "github.com/kVinsom/Bank-repository-service/pkg/core"
)

// MockIDepositService is a mock of IDepositService interface.
type MockIDepositService struct {
	ctrl     *gomock.Controller
	recorder *MockIDepositServiceMockRecorder
}

// MockIDepositServiceMockRecorder is the mock recorder for MockIDepositService.
type MockIDepositServiceMockRecorder struct {
	mock *MockIDepositService
}

// NewMockIDepositService creates a new mock instance.
func NewMockIDepositService(ctrl *gomock.Controller) *MockIDepositService {
	mock := &MockIDepositService{ctrl: ctrl}
	mock.recorder = &MockIDepositServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDepositService) EXPECT() *MockIDepositServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIDepositService) Create(arg0 context.Context, arg1 *core.DepositCreateInput) (*core.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*core.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIDepositServiceMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIDepositService)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockIDepositService) Delete(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIDepositServiceMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIDepositService)(nil).Delete), arg0, arg1)
}

// GetAll mocks base method.
func (m *MockIDepositService) GetAll(arg0 context.Context) ([]core.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0)
	ret0, _ := ret[0].([]core.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockIDepositServiceMockRecorder) GetAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockIDepositService)(nil).GetAll), arg0)
}

// GetById mocks base method.
func (m *MockIDepositService) GetById(arg0 context.Context, arg1 int64) (*core.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", arg0, arg1)
	ret0, _ := ret[0].(*core.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockIDepositServiceMockRecorder) GetById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockIDepositService)(nil).GetById), arg0, arg1)
}

// GetByUser mocks base method.
func (m *MockIDepositService) GetByUser(arg0 context.Context, arg1 int64) ([]core.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUser", arg0, arg1)
	ret0, _ := ret[0].([]core.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUser indicates an expected call of GetByUser.
func (mr *MockIDepositServiceMockRecorder) GetByUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUser", reflect.TypeOf((*MockIDepositService)(nil).GetByUser), arg0, arg1)
}

// Replenish mocks base method.
func (m *MockIDepositService) Replenish(arg0 context.Context, arg1 int64, arg2 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Replenish", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Replenish indicates an expected call of Replenish.
func (mr *MockIDepositServiceMockRecorder) Replenish(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replenish", reflect.TypeOf((*MockIDepositService)(nil).Replenish), arg0, arg1, arg2)
}
