// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	core "github.com/Suinar/Bank-exhange-rate-service/pkg/core"
	gomock "github.com/golang/mock/gomock"
)

// MockIExchangeRateService is a mock of IExchangeRateService interface.
type MockIExchangeRateService struct {
	ctrl     *gomock.Controller
	recorder *MockIExchangeRateServiceMockRecorder
}

// MockIExchangeRateServiceMockRecorder is the mock recorder for MockIExchangeRateService.
type MockIExchangeRateServiceMockRecorder struct {
	mock *MockIExchangeRateService
}

// NewMockIExchangeRateService creates a new mock instance.
func NewMockIExchangeRateService(ctrl *gomock.Controller) *MockIExchangeRateService {
	mock := &MockIExchangeRateService{ctrl: ctrl}
	mock.recorder = &MockIExchangeRateServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIExchangeRateService) EXPECT() *MockIExchangeRateServiceMockRecorder {
	return m.recorder
}

// GetAllRanking mocks base method.
func (m *MockIExchangeRateService) GetAllRanking(arg0 context.Context, arg1 int) ([]core.Ranking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllRanking", arg0, arg1)
	ret0, _ := ret[0].([]core.Ranking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllRanking indicates an expected call of GetAllRanking.
func (mr *MockIExchangeRateServiceMockRecorder) GetAllRanking(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllRanking", reflect.TypeOf((*MockIExchangeRateService)(nil).GetAllRanking), arg0, arg1)
}

// GetRelativeRanking mocks base method.
func (m *MockIExchangeRateService) GetRelativeRanking(arg0 context.Context, arg1, arg2 int) (*core.Ranking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRelativeRanking", arg0, arg1, arg2)
	ret0, _ := ret[0].(*core.Ranking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRelativeRanking indicates an expected call of GetRelativeRanking.
func (mr *MockIExchangeRateServiceMockRecorder) GetRelativeRanking(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelativeRanking", reflect.TypeOf((*MockIExchangeRateService)(nil).GetRelativeRanking), arg0, arg1, arg2)
}
